import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Super Vinyl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/purecss@2.1.0/build/pure-min.css"
          integrity="sha384-yHIFVG6ClnONEA5yB5DJXfW2/KC173DIQrYoZMEtBvGzmf0PKiGyNEqe9N6BNDBH"
          crossOrigin="anonymous"
        />
      </Head>

      <main className="pure-g">
        <div className="pure-u-1-3">
          <h1 className={styles.title}>Super Vinyl</h1>
        </div>
        <div className="pure-u-1-3"></div>
      </main>
    </div>
  );
};

export default Home;
